select  * from apex_application_page_ir s where APPLICATION_ID = 600 and NUMBER_OF_PRIVATE_REPORTS <> 0	;
select  * from apex_application_page_ir_rpt s where APPLICATION_ID = 600;

CREATE TABLE TEMP_apex_application_page_ir_rpt AS
select R.* from apex_application_page_ir_rpt r ,apex_application_page_ir s   where s.REGION_ID	 = r.REGION_ID  and s.APPLICATION_ID = 600  


CREATE TABLE TEMP_apex_application_page_ir AS
select S.* from apex_application_page_ir_rpt r ,apex_application_page_ir s   where s.REGION_ID	 = r.REGION_ID  and s.APPLICATION_ID = 600  


SELECT COUNT(1) FROM apex_application_page_ir R, TEMP_apex_application_page_ir I WHERE I.PAGE_ID = R.PAGE_ID AND R.APPLICATION_ID = I.APPLICATION_ID AND R.NUMBER_OF_COLUMNS = I.NUMBER_OF_COLUMNS AND I.REGION_NAME = R.REGION_NAME



create table TEMP_wwv_flow_worksheet_rpts as 
select * from apex_230200.wwv_flow_worksheet_rpts where flow_id = 600  AND session_id IS NULL AND APPLICATION_USER <> 'APXWS_DEFAULT';


CREATE TABLE TEMP_wwv_flow_worksheets AS
SELECT * FROM  apex_230200.wwv_flow_worksheets s WHERE FLOW_ID = 600 

  

DECLARE
L_WORKSHEET_ID NUMBER;
L_SECURITY_GROUP_ID NUMBER:=54497890482147580;
begin

FOR I IN (SELECT  S.* , P.ID AS WID FROM  TEMP_WWV_FLOW_WORKSHEET_RPTS P , TEMP_WWV_FLOW_WORKSHEETS S WHERE S.ID = P.WORKSHEET_ID) LOOP
BEGIN
SELECT DISTINCT ID  INTO L_WORKSHEET_ID FROM apex_230200.WWV_FLOW_WORKSHEETS  WHERE FLOW_ID = I.FLOW_ID AND PAGE_ID = I.PAGE_ID AND INTERNAL_UID = I.INTERNAL_UID  ;  

Insert into apex_230200.wwv_flow_worksheet_rpts (ID,
WORKSHEET_ID,FLOW_ID,PAGE_ID,
SESSION_ID,TENANT_ID,BASE_REPORT_ID,
APPLICATION_USER,NAME,DESCRIPTION,REPORT_SEQ,
REPORT_TYPE,REPORT_ALIAS,STATUS,VIEW_MODE,CATEGORY_ID,AUTOSAVE,IS_DEFAULT,DISPLAY_ROWS,PAGINATION_MIN_ROW,REPORT_COLUMNS,SORT_COLUMN_1,
SORT_DIRECTION_1,SORT_COLUMN_2,SORT_DIRECTION_2,SORT_COLUMN_3,SORT_DIRECTION_3,SORT_COLUMN_4,SORT_DIRECTION_4,SORT_COLUMN_5,SORT_DIRECTION_5,SORT_COLUMN_6,
SORT_DIRECTION_6,BREAK_ON,BREAK_ENABLED_ON,CONTROL_BREAK_OPTIONS,SUM_COLUMNS_ON_BREAK,AVG_COLUMNS_ON_BREAK,MAX_COLUMNS_ON_BREAK,MIN_COLUMNS_ON_BREAK,MEDIAN_COLUMNS_ON_BREAK,
MODE_COLUMNS_ON_BREAK,COUNT_COLUMNS_ON_BREAK,COUNT_DISTNT_COL_ON_BREAK,FLASHBACK_MINS_AGO,FLASHBACK_ENABLED,CHART_TYPE,CHART_3D,CHART_LABEL_COLUMN,CHART_LABEL_TITLE,CHART_VALUE_COLUMN,
CHART_AGGREGATE,CHART_VALUE_TITLE,CHART_SORTING,CHART_ORIENTATION,CALENDAR_DATE_COLUMN,CALENDAR_DISPLAY_COLUMN,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,SECURITY_GROUP_ID
) SELECT NULL,L_WORKSHEET_ID,FLOW_ID,PAGE_ID,
SESSION_ID,TENANT_ID,BASE_REPORT_ID,
APPLICATION_USER,NAME,DESCRIPTION,REPORT_SEQ,
REPORT_TYPE,REPORT_ALIAS,STATUS,VIEW_MODE,CATEGORY_ID,AUTOSAVE,IS_DEFAULT,DISPLAY_ROWS,PAGINATION_MIN_ROW,REPORT_COLUMNS,SORT_COLUMN_1,
SORT_DIRECTION_1,SORT_COLUMN_2,SORT_DIRECTION_2,SORT_COLUMN_3,SORT_DIRECTION_3,SORT_COLUMN_4,SORT_DIRECTION_4,SORT_COLUMN_5,SORT_DIRECTION_5,SORT_COLUMN_6,
SORT_DIRECTION_6,BREAK_ON,BREAK_ENABLED_ON,CONTROL_BREAK_OPTIONS,SUM_COLUMNS_ON_BREAK,AVG_COLUMNS_ON_BREAK,MAX_COLUMNS_ON_BREAK,MIN_COLUMNS_ON_BREAK,MEDIAN_COLUMNS_ON_BREAK,
MODE_COLUMNS_ON_BREAK,COUNT_COLUMNS_ON_BREAK,COUNT_DISTNT_COL_ON_BREAK,FLASHBACK_MINS_AGO,FLASHBACK_ENABLED,CHART_TYPE,CHART_3D,CHART_LABEL_COLUMN,CHART_LABEL_TITLE,CHART_VALUE_COLUMN,
CHART_AGGREGATE,CHART_VALUE_TITLE,CHART_SORTING,CHART_ORIENTATION,CALENDAR_DATE_COLUMN,CALENDAR_DISPLAY_COLUMN,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,L_SECURITY_GROUP_ID
FROM TEMP_WWV_FLOW_WORKSHEET_RPTS WHERE ID = I.WID ; 

EXCEPTION WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE(I.ID  || SQLERRM );
END;
end LOOP;
END;



